### ISSUE TITLE
Status panel view error when using service account on Grafana Cloud

### ISSUE THREAD

**Issue by abudavis** [grafana/Grafana_Status_panel#14]
Have installed the plugin status panel and I am able to use it on Grafana Cloud.
The status panel plugin works on a regular dashboard but when I use a service account the panel doesn't work for someone using an LED T.V

Following is the error. I tried to give almost every access there is to the service account, but still face the issue. Please suggest.

```
importPanelPlugin.ts:90 Error loading panel plugin: vonage-status-panel Error: Could not load plugin: Error: 401 , loading https://plugins-cdn.grafana.net/vonage-status-panel/2.0.2/public/plugins/vonage-status-panel/module.js (SystemJS Error#7 https://github.com/systemjs/systemjs/blob/main/docs/errors.md#7)
at plugin_loader.ts:126:17
at Mt.invoke (zone.js:369:28)
at Ve.run (zone.js:111:43)
at zone.js:2538:40
at Mt.invokeTask (zone.js:402:33)
at Ve.runTask (zone.js:159:47)
at Ie (zone.js:581:35)
```

**Comment by tolzhabayev** [comment]
Hey, since you are in Grafana Cloud can you open a support ticket so that we can take a look at your instance https://grafana.com/docs/grafana-cloud/account-management/support/?

We assume it should be resolved by this PR https://github.com/grafana/grafana/pull/97162 which should already be rolled out.

**Comment by abudavis** [comment]
@tolzhabayev It already raised it with them and this is what they said. If its already rolled out what version is it fixed and what should Grafana Cloud do to update the plugin?

--
When it comes to this 3rd party plugin we can't provide much support. This plugin is fairly old and isn't maintained by Grafana, so it is not in scope for us sadly. I would suggest next steps be to open a GitHub issue on the plugin page to see if the maintainers can work on the possible bug.
--

**Comment by tolzhabayev** [comment]
Closing this is the issue was related to our cloud environment in general and not the status panel in particular.
